### ISSUE TITLE
Remove Bottom Space

### ISSUE THREAD

**Issue by Dhaval2404** [wajahatkarim3/MediumClap-Android#10]
Is it possible to remove extra space from the bottom? I want to set Clap Fab at the bottom-end, just like normal FAB. But it leaves so to much space at the bottom.

I have just checked that in [clap_fab_layout](https://github.com/wajahatkarim3/MediumClap-Android/blob/master/clapfab/src/main/res/layout/clap_fab_layout.xml) file, parent layout(RelativeLayout) height is set as "match_parent". Can it be set to "wrap_content"?

**Comment by wajahatkarim3** [comment]
Thank you for letting me know about this. Let me fix it and upload on jcenter.

**Comment by Dhaval2404** [comment]
@wajahatkarim3 Thank you very much for the quick fix. 👍

**Comment by Dhaval2404** [comment]
@wajahatkarim3 version 1.0.2 has introduced alignment issue in clap fab. Can you please look into it.  I have also created a [pull request](https://github.com/wajahatkarim3/MediumClap-Android/pull/12), Please take a look.

**Comment by wajahatkarim3** [comment]
Hello @Dhaval2404 . Thanks for your contributions 👍 Much appreciated. I have merged the code and I also have uploaded new release on jcenter of [version 1.0.3](https://github.com/wajahatkarim3/MediumClap-Android/releases/tag/1.0.3)

**Comment by Dhaval2404** [comment]
@wajahatkarim3 Thank you very much.!!
