### ISSUE TITLE
Not able to set Clap Count

### ISSUE THREAD

**Issue by chaya222** [wajahatkarim3/MediumClap-Android#17]
I am trying to set a default value for clap count when i enter an activity. I saw a attribute named _**app:cf_format_clap_count="false"**_  in the sample app but i didn't find it. Can you help me out.

**Comment by wajahatkarim3** [comment]
Yes, this attribute was added in the pull request #16 but it's not available on ```jcenter()``` yet for the use. I will upload new version on ```jcenter()``` in few minutes and will let you know 😄 
Thank you for using Medium Clap 👍

**Comment by chaya222** [comment]
Hi Karim 
can u please upload new version on  jcenter() today ? , i have some task to complete today only.
Thanks

**Comment by wajahatkarim3** [comment]
Hi @chaya222 ,
New version [```1.0.4```](https://github.com/wajahatkarim3/MediumClap-Android/releases/tag/1.0.4) has been uploaded on ```jcenter()```. Read Me file has also been updated accordingly with two new attributes added:

* Added option to set default clap count. It will be very helpful to set clap count from the rest API response.
```
To set clap count from xml:
    app:cf_clap_count="10"
To set clap count programatically:
     clapFAB.setClapCount(10)
```
* Added option to format clap count(Will be helpful when count increase beyond 999). Formatter will be enabled by default.
```
To enable/disable formatter:
    app:cf_format_clap_count="true"
    app:cf_format_clap_count="false"
````
