### ISSUE TITLE
long press clap count is not getting increased.

### ISSUE THREAD

**Issue by chaya222** [wajahatkarim3/MediumClap-Android#19]

**Comment by wajahatkarim3** [comment]
Medium Clap doesn't support long clap actually. I am curious why you need long clap? Maybe we can add it.

**Comment by chaya222** [comment]
actually i work in a company where we have both android and ios app . This functionality is there in ios app thats why i need that functionality if you can add it will be a great help

**Comment by wajahatkarim3** [comment]
I will try to do it today but the schedule is tough these days. 😢

**Comment by wajahatkarim3** [comment]
The new version `1.0.5` is now available on `jcenter()` for use. You can do it so by using these two new attributes:
```xml
app:cf_long_press_enabled="false"
app:cf_long_press_clap_interval="300"
```

**Comment by mmfarzaneh** [comment]
How can i handle long click and click together?

**Comment by wajahatkarim3** [comment]
Well, they work in a similar way. Click increases count by 1 and long click keeps increasing until the touch is stopped or count is reached maximum count.

**Comment by mmfarzaneh** [comment]
in your new version , increasing by click does not work and just long click working ?

**Comment by wajahatkarim3** [comment]
So, I just tested it, and you are right unfortunately 😢 
So, if disable long click, then click also doesn't work. Let me check. T
Thanks for letting me know 👍

**Comment by mmfarzaneh** [comment]
tanks

**Comment by wajahatkarim3** [comment]
The new version [`1.0.6`](https://github.com/wajahatkarim3/MediumClap-Android/releases/tag/1.0.6) is now available on `jcenter()` for use. This fixes the conflict between click and long press issue as pointed out by @mmfarzaneh .
