### ISSUE TITLE
any method to change colour of circle enclosing icon?

### ISSUE THREAD

**Issue by SrikalyanBurra** [wajahatkarim3/MediumClap-Android#8]

**Comment by wajahatkarim3** [comment]
The ```ClapFAB``` extends ```FloatingActionButton``` from support library, so you can change the color of it by using same methods as you do with any ```FloatingActionButton```. For example, you can read about it on this SO thread at https://stackoverflow.com/questions/30969455/android-changing-floating-action-button-color
